### PR TITLE
handing _parse errors a little better

### PR DESCRIPTION
**Pull request by jmervine**
Addressing https://github.com/MaxCDN/node-maxcdn/issues/15

@bedeoverend feedback welcome, I think this what you had in mind.

### CODE REVIEW

**Comment by bedeoverend** [comment]
@jmervine Ah so what I was proposing was something like this:
```js
MaxCDN.prototype._parse = function _parse(callback) {
    return function(err, data, response) {
        var parseError;
        try {
            data = JSON.parse(data);
        } catch(e) {
            parseError = {
                statusCode: 500,
                data: 'Invalid JSON from MaxCDN\'s API.'
            };
        }
        callback(err || parseError, data);
    };
};
```

The problem I was facing was `err` was set and `body` was undefined, meaning that it was always getting a parse error, when really it should have just sent through the original error. The above code should default to the `err` passed through from the response e.g. a `400` or `500` error, then if parsing failed, it should fall back to the `parseError`, otherwise everything's ok and it returns parsed data. Does that make sense?

**Comment by jmervine** [comment]
@bedeoverend If we're looking at something like that, I think I'd rather handle it like this...

```node
MaxCDN.prototype._parse = function _parse(callback) {
    return function(err, data, response) {
        var parseError;
        try {
            data = JSON.parse(data);
        } catch(e) {
            return callback(e, {
                statusCode: 500,
                data: 'Invalid JSON from MaxCDN\'s API.'
            });
        }
        return callback(err, data);
    };
};
```

As I don't want to return a JSON body in place of an error, as it would violate what's expected. Thoughts?

**Comment by bedeoverend** [comment]
@jmervine Fair enough - I'd propose the following if that was the case:

```js
MaxCDN.prototype._parse = function _parse(callback) {
    return function(err, data, response) {
        if (err) {
          return callback(err, data);
        }

        try {
            data = JSON.parse(data);
        } catch(e) {
            return callback(e, {
                statusCode: 500,
                data: 'Invalid JSON from MaxCDN\'s API.'
            });
        }

        return callback(err, data);
    };
};
```

e.g. I recently was getting an `ECONNRESET` error. So `_parse` was being called like so: `_parse(ECONNRESET_ERROR, undefined, undefined)`. With the current way, and the above proposal, the SDK was throwing `500 'Invalid JSON from MaxCDN\'s API.'` as it tried to parse `undefined`, when it should have returned an `ECONNRESET`. The proposal included here would intercept that `ECONNRESET`, return it, and not attempt to parse an `undefined` body.

Another option would be:

```js
MaxCDN.prototype._parse = function _parse(callback) {
    return function(err, data, response) {
        if (typeof data !== 'undefined') {
          try {
              data = JSON.parse(data);
          } catch(e) {
              return callback(e, {
                  statusCode: 500,
                  data: 'Invalid JSON from MaxCDN\'s API.'
              });
          }
        }

        return callback(err, data);
    };
};
```

Though IMO I feel the first one is safer incase you still get a response error and non-parsable JSON data.

**Comment by jmervine** [comment]
I like the first one with a slight tweak...

```javascript
MaxCDN.prototype._parse = function _parse(callback) {
    return function(err, data, response) {
        if (err === undefined) {
            try {
                data = JSON.parse(data);
            } catch(e) {
                return callback(e, {
                    statusCode: 500,
                    data: 'Invalid JSON from MaxCDN\'s API.'
                });
            }
        }

        return callback(err, data);
    };
};
```

**Comment by bedeoverend** [comment]
Great! LGTM. Thanks @jmervine

**Comment by jmervine** [comment]
I'll cut a release this weekend at some point as long as my wife doesn't go in to labor before I get a chance. 😝

**Comment by bedeoverend** [comment]
No worries @jmervine - all the best to you and your wife! I'd say that's a very reasonable reason to delay a release 😉

**Comment by jmervine** [comment]
Integration tests showed that `null` is actually returned, not `undefined`.  Might want to dig in to that in the future, but for now, handling both.

**Comment by jmervine** [comment]
@bedeoverend Thanks for your feedback and help on this!

**Comment by jmervine** [comment]
released as 0.2.1 here: https://www.npmjs.com/package/maxcdn

**Comment by bedeoverend** [comment]
@jmervine welcome - thanks for the patch!

**Pull request merged**
